### ISSUE TITLE
Gem Load Error is: uninitialized constant Hashie::Extensions::RubyVersionCheck::ClassMethods::RubyVersion

### ISSUE THREAD

**Issue by BjornMelgaard** [mkdynamic/omniauth-facebook#268]
```
$ rails s                          
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'omniauth-facebook'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Hashie::Extensions::RubyVersionCheck::ClassMethods::RubyVersion
Backtrace for gem load error is:
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/hashie-3.5.0/lib/hashie/extensions/ruby_version_check.rb:10:in `with_minimum_ruby'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/hashie-3.5.0/lib/hashie/array.rb:8:in `<class:Array>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/hashie-3.5.0/lib/hashie/array.rb:5:in `<module:Hashie>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/hashie-3.5.0/lib/hashie/array.rb:4:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/hashie-3.5.0/lib/hashie/mash.rb:2:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-1.3.2/lib/omniauth/strategy.rb:1:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:15:in `<class:OAuth2>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:14:in `<module:Strategies>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:8:in `<module:OmniAuth>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:7:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-facebook-4.0.0/lib/omniauth/strategies/facebook.rb:1:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-facebook-4.0.0/lib/omniauth/facebook.rb:2:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/omniauth-facebook-4.0.0/lib/omniauth-facebook.rb:1:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
/home/bjorn/projects/rails-bookstore/config/application.rb:17:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/home/bjorn/projects/rails-bookstore/bin/rails:9:in `require'
/home/bjorn/projects/rails-bookstore/bin/rails:9:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bjorn/projects/rails-bookstore/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Bundler Error Backtrace:
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `each'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:86:in `block in require'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `each'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler/runtime.rb:75:in `require'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/bundler-1.14.3/lib/bundler.rb:107:in `require'
	from /home/bjorn/projects/rails-bookstore/config/application.rb:17:in `<top (required)>'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /home/bjorn/projects/rails-bookstore/bin/rails:9:in `require'
	from /home/bjorn/projects/rails-bookstore/bin/rails:9:in `<top (required)>'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
	from /home/bjorn/.rvm/gems/ruby-2.4.0@rails-bookstore/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
	from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bjorn/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/bjorn/projects/rails-bookstore/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

```

:astonished:

**Comment by BjornMelgaard** [comment]
https://github.com/intridea/hashie/issues/391
